[config]
model="claude-3-5-sonnet"
use_wiki_settings_file=false

[pr_code_suggestions]
rank_suggestions = true
extra_instructions = """\
Make code efficiency and style suggestions using the Google style guide documentation (https://google.github.io/styleguide/go/best-practices and https://google.github.io/styleguide/go/decisions) and the effective go documentation (https://golang.org/doc/effective_go.html)
"""
