backend:
  # The log level can be one of debug, info, warn and error.
  # https://pkg.go.dev/log/slog#Level
  log_level: debug
  log_file: backend.log
  downloader:
    # Location where downloaded malware will be stored.
    malware_download_dir: /home/niels/malware/
    # The malware downloaded HTTP client timeout. This should be relatively high
    # because sometimes malware is served from very slow IoT devices.
    http_timeout: 10m
  listener:
    # IP and port where the backend needs to listen on.
    listen_address: localhost:41110
    # The following SSL options are optional; use them for SSL server and client
    # authentication.
    ssl_cert: path/to/server-cert.pem
    ssl_key: path/to/server-key.pem
    ssl_ca_cert: path/to/ca-cert.pem

  database:
    # URL to the postgresql database
    url: postgres://username:password@localhost/lophiid
    # How many open concurrent database connections are allowed.
    max_open_connections: 30
    # How many connections to keep open all the time.
    min_open_connections: 10

  advanced:
    # How long to cache Content's that were fetched from the database.
    content_cache_duration: 30m
    # How long to cache download URLs which prevents them from being fetched
    # again if seen multiple times in a row during this time. Don't set this
    # too long because attacker payloads change over time and it's interesting
    # to track this by refetching the same payload URLs.
    download_cache_duration: 5m
    # How long to keep track of requests coming from the same attacker.
    attack_tracking_duration: 168h # week


alerting:
  # The alerting interval.  Alerts are aggregated and send every <interval>.
  interval: 2m
  telegram:
    # Telegram API key and channel ID.
    api_key: AAAAAAAAAAAAAAAAAAAA
    channel_id: 111111

virustotal:
  # Your virus total API key.
  api_key: AAAAAAAAAAAAAAAAAA
  # HTTP timeout for communication with virustotal.
  http_timeout: 2m

prometheus:
  listen_address: 127.0.0.1:8998

whois_manager:
  client_timeout: 2s
  cache_expiration_time: 12h
  max_attempts: 3
